# Generated by Django 2.1.3 on 2018-12-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('capital', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=2)),
                ('population', models.PositiveIntegerField(default=0)),
                ('area', models.PositiveIntegerField(default=0)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='countrydata.Continent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
