# Generated by Django 2.1.3 on 2018-12-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0002_auto_20181202_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='country',
            order_with_respect_to=None,
        ),
    ]
