# Generated by Django 2.1.3 on 2018-12-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0003_auto_20181202_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
