# Generated by Django 2.1.3 on 2018-12-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0004_auto_20181202_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2),
        ),
    ]
