# Generated by Django 2.1.3 on 2018-12-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0005_auto_20181202_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
    ]
