# Generated by Django 2.1.3 on 2018-12-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrydata', '0007_auto_20181202_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(max_length=200),
        ),
    ]
